name: Deb
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_deb:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ubuntu-latest
    steps:
      - name: Enable qemu-user-static
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Run in container
        run: |
          docker run --platform linux/${{ matrix.arch }} --rm 84codes/crystal:1.1.1-${{ matrix.os }} sh -c \
          "set -eux &&
           apt-get update &&
           apt-get install -y libsystemd-dev dpkg fakeroot help2man lintian git tzdata curl &&
           git clone ${{ github.server_url }}/${{ github.repository }}.git &&
           cd websocket-tcp-relay &&
           build/deb &&
           . /etc/os-release &&
           curl -fsSO -u ${{ secrets.PACKAGECLOUD_TOKEN }}: https://packagecloud.io/api/v1/distributions.json &&
           dist_id=$(jq '.deb[] | select(.index_name == \"${ID}\").versions[] | select(.index_name == \"${VERSION_CODENAME}\").id' distributions.json) &&
           debfile=$(find builds -name '*.deb' | tail -1) &&
           curl -fsS -u ${{ secrets.PACKAGECLOUD_TOKEN }}: -XPOST https://packagecloud.io/api/v1/repos/cloudamqp/amqproxy/packages.json -F \"package[distro_version_id]=${dist_id}\" -F \"package[package_file]=@${debfile}\"
          "
