name: Deb
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_deb:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version
        run: echo "PKG_VERSION=$(git describe --tags | cut -c2-)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image that will build a deb pkg and upload it to PackageCloud
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.deb
          platforms: linux/${{ matrix.arch }}
          build-args: |
            baseimage=84codes/crystal:1.1.1-${{ matrix.os }}
            pkg_version=${{ env.PKG_VERSION }}
            packagecloud_token=${{ secrets.PACKAGECLOUD_TOKEN }}
