name: Deb
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_deb:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ubuntu-latest
    steps:
      - name: Enable qemu-user-static
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Run in container
        run: |
          docker run --platform linux/${{ matrix.arch }} --rm 84codes/crystal:1.1.1-${{ matrix.os }} sh -c \
          "set -eux &&
            apt-get update &&
            apt-get install -y libsystemd-dev dpkg fakeroot help2man lintian build-essential gcc pkg-config git tzdata libpcre3-dev libevent-dev libyaml-dev libgmp-dev libssl-dev libxml2-dev &&
            git clone ${{ github.server_url }}/${{ github.repository }} &&
            cd websocket-tcp-relay &&
            build/deb
          "

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install packagecloud cli
        run: gem install --no-document package_cloud

      - name: Upload to packagecloud release repo
        run: package_cloud push cloudamqp/websocket-tcp-relay/ubuntu/${{ env.CODENAME }} builds/debian/${{ env.CODENAME }}/websocket-tcp-relay_${{ env.VERSION }}-1_${{ matrix.arch }}.deb
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
